---
title: "中介效应分析"
subtitle: ""
author: "冯凌秉"
institute: "<span style = 'font-size: 70%;'>
  江西财经大学 <br> 
  产业经济研究院</span>"
date: '2020<br><br>
  `r icon::fa("paper-plane")` <feng.lingbing@jxufe.edu.cn>'
output:
  xaringan::moon_reader:
    css: [default, zh-CN.css]
    lib_dir: libs
    includes:
      after_body: insert-logo.html
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---
```{r, setup, include=FALSE,echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = ">", 
                      fig.retina = 3, warning = FALSE, message = FALSE)
library(RefManageR)
library(AER)
library(stargazer)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(mediation) #Mediation package
library(rockchalk) #Graphing simple slopes; moderation
library(multilevel) #Sobel Test
library(bda) #Another Sobel Test option
library(gvlma)
BibOptions(check.entries = FALSE, bib.style = "authoryear", style = "markdown", dashed = TRUE)
bib <- ReadBib("bib1.bib")
css.fig <- list(
    css.depvarhead = 'color: red;',
    css.centeralign = 'text-align: left;', 
    css.firsttablecol = 'font-weight: bold;', 
    css.summary = 'color: blue;'
  )
```

```{r}
set.seed(123) #Standardizes the numbers generated by rnorm; see Chapter 5
N <- 100 #Number of participants; graduate students
X <- rnorm(N, 175, 7) #IV; hours since dawn
M <- 0.7*X + rnorm(N, 0, 5) #Suspected mediator; coffee consumption 
Y <- 0.4*M + rnorm(N, 0, 5) #DV; wakefulness
Meddata <- data.frame(X, M, Y)
```

Baron & Kenny (1986) 四步法：

1. Y 对 X回归，估计总效应系数c

2. X 对 M回归，估计系数a，

3. M 对 Y和X回归，

4，Y对X和M回归。

---
# 总效应

```{r}
fit <- lm(Y ~ X, data=Meddata)
summary(fit)
```
$\hat{c}=$ `r coef(fit)[2]`.
---
# A 路径
```{r}
fita <- lm(M ~ X, data=Meddata)
summary(fita)
```

$\hat{a}=$ `r coef(fita)[2]`.
---
# B通道
```{r}
fitb <- lm(Y ~ M + X, data=Meddata)
summary(fitb)
```
$\hat{b}=$ `r coef(fitb)[2]`, $\hat{c\prime}=$ `r coef(fitb)[3]`

---
# Sobel 检验
```{r}
library(multilevel)
sobel(Meddata$X, Meddata$M, Meddata$Y)
```

---
# Bootstrap 检验
Preacher & Hayes (2004)
```{r}
fitM <- lm(M ~ X,     data=Meddata)
fitY <- lm(Y ~ X + M, data=Meddata)
fitMed <- mediate(fitM, fitY, treat="X", mediator="M")
summary(fitMed)
```
---



```{r}
plot(fitMed)
```

---
# Bootstrap
```{r}
fitMedBoot <- mediate(fitM, fitY, boot=TRUE, sims=999, treat="X", mediator="M")
summary(fitMedBoot)
```

---
```{r}
plot(fitMedBoot)
```


---
# 中介效应结果解释

ACME：（Average Causal Mediation Effects)：间接效应 = 总效应 - 直接效应。

ADE：（average Direct Effect) 直接效应

Total Effects: 总效应 = 直接效应 + 中介效应


